# Python Numpy - Assignment

# 1. Import the package numpy as np.

In [1]:
import numpy as np

# 2. Create 1D array "a1" from the list and display the properties.

In [2]:
l1 = list(range(1,20))
a1 = np.array(l1)

In [4]:
#type of a1 object
type(a1)

numpy.ndarray

In [5]:
#dimmension of a1 object
a1.ndim

1

In [6]:
#size of a1 array
a1.size

19

# 3. Create 2D array "a2" of one digit random numbers with shape (4, 5) and display the properties.

In [24]:
### 2D array Creation
a2 = np.random.randint(1,10,(4,5))

In [25]:
# displaying the properties of a2 array
type(a2)

numpy.ndarray

In [26]:
# total number of elements available in a2 array
a2.size

20

In [27]:
# number of dimmension of a2 array
a2.ndim

2

In [29]:
# data type of a2 array
a2.dtype

dtype('int32')

# 4. Get only first row from a2.

In [41]:
a2[0,]

array([7, 9, 8, 2, 7])

# 5. Get only last column from a2.

In [42]:
a2[:,-1]

array([7, 9, 8, 6])

# 6. Get the value at position 2, 4.

In [49]:
### 2nd Position Value
a2[0,1]

9

In [50]:
### 4th Position Value
a2[0,4]

7

# 7. Get the data from first two rows and last three columns.

In [54]:
a2[0:2,-3:]

array([[8, 2, 7],
       [6, 2, 9]])

# 8. Add number 100 to elements in array a2.

In [56]:
a2 * 100

array([[700, 900, 800, 200, 700],
       [500, 500, 600, 200, 900],
       [200, 100, 200, 300, 800],
       [500, 200, 500, 600, 600]])

# 9. get the values which are greater than the overall average.

In [59]:
a2[a2 > np.mean(a2)]

array([7, 9, 8, 7, 6, 9, 8, 6, 6])

# 10. Create a numpy array a3 with 20 equidistant elements in range 1, 5.

In [65]:
a3 = np.linspace(1,5,20)

In [64]:
a3

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

# 11. Create (3, 5) ndarray with numbers starting 11 till 25 (numbers should not repeat) & save in a4.

In [66]:
a4 = np.arange(11,26).reshape(3,5)

In [72]:
a4

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

# 12. Get the values from a4 which are less than 15 and greater than 20.

In [79]:
result = a4[(a4 < 15) | (a4 > 20)]

In [80]:
print(result)

[11 12 13 14 21 22 23 24 25]
